[workspace]

members = [
    # code shared across daily solutions
    "prob",

    # cli
    "aoc",

    # daily solutions
    "day01",
    "day02",
    "day03",
    "day04",
    "day05",
    "day06",
    "day07",
]