[package]
name = "aoc"
version = "0.1.0"
authors = ["Michael Collins <michael.collins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day01 = { path = "../day01" }
prob = {path = "../prob" }
